---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
ratings:
  paths:
  - "packages/**.js"
exclude_paths:
- config/**/*
- tests/**/*
- server/**/*
- scripts/**/*
- generators/**/*
- bin/**/*
